"""Scraper for Hefner's Custard (Cedarburg, WI)."""

from app.scrapers.scraper_base import BaseScraper

HEFNERS_URL = "https://www.hefnerscustard.com/"


class HefnersScraper(BaseScraper):
    """Scraper for Hefner's Custard."""

    def __init__(self):
        super().__init__("hefners", "Hefner's")

    def scrape(self):
        """Scrape Hefner's Custard flavor of the day."""
        self.log_start()

        if not self.locations:
            self.log_error("No locations found")
            return []

        location = self.locations[0]
        location_name = location.get("name", self.brand)
        location_url = location.get("url", HEFNERS_URL)

        self.log_location(location_name, location_url)

        try:
            html = self.get_html(location_url)
            if not html:
                self.log_error("Failed to get HTML")
                return []

            flavor_name, description = self._extract_flavor(html)

            if not flavor_name:
                self.log_error("No flavor of the day found")
                return []

            self.log_flavor("Hefner's", flavor_name)

            flavor_entry = self.create_flavor(
                location_name,
                flavor_name,
                description or "",
                None,
                url=location_url,
                location_id=location.get("id"),
                lat=location.get("lat"),
                lng=location.get("lng"),
                address=location.get("address"),
            )
            self.log_complete(1)
            return [flavor_entry]

        except Exception as e:
            self.log_error(f"Failed to scrape: {e}", exc_info=True)
            return []

    def _extract_flavor(self, html):
        """
        Extract flavor name and description from the Hefner's homepage.

        The page structure has multiple h3 tags:
        - First h3: The flavor of the day (e.g., "Chocolate Truffle")
        - Subsequent h3: Monthly specials (Shake, Sundae, Sandwich/Lobster Roll, etc.)

        The "FLAVOR OF THE DAY" label text is generated by CSS or split across elements,
        so we identify the flavor by finding the first h3 that isn't a monthly special.

        Returns:
            tuple: (flavor_name, description) or (None, None) if not found
        """
        # Keywords that indicate monthly specials (NOT the daily flavor)
        monthly_keywords = ["SHAKE", "SUNDAE", "SANDWICH", "ROLL", "BURGER"]

        # Find all h3 tags
        h3_tags = html.find_all("h3")

        for h3 in h3_tags:
            flavor_name = h3.get_text(strip=True)

            # Skip if empty or too short
            if not flavor_name or len(flavor_name) < 3:
                continue

            # Skip if it matches a monthly special keyword
            flavor_upper = flavor_name.upper()
            if any(keyword in flavor_upper for keyword in monthly_keywords):
                continue

            # This is likely the flavor of the day
            # Look for description in the next sibling <p>
            description = ""
            next_elem = h3.find_next_sibling()
            # Skip whitespace/empty elements
            while next_elem and next_elem.name not in ("p", "h3", "h2", "div"):
                next_elem = next_elem.find_next_sibling()
            if next_elem and next_elem.name == "p":
                desc_text = next_elem.get_text(strip=True)
                if desc_text and len(desc_text) > 5:
                    description = desc_text

            return flavor_name, description

        self.logger.error("No valid flavor h3 found (all were monthly specials)")
        return None, None


def scrape_hefners():
    """Scrape Hefner's - called by generate_flavors.py."""
    scraper = HefnersScraper()
    return scraper.scrape()
